/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Copie: typeof import('./components/CrcaForm - Copie.vue')['default']
    CrcaForm: typeof import('./components/CrcaForm.vue')['default']
    CrfmForm: typeof import('./components/CrfmForm.vue')['default']
    DsfrAlert: typeof import('@gouvminint/vue-dsfr')['DsfrAlert']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrCheckbox: typeof import('@gouvminint/vue-dsfr')['DsfrCheckbox']
    DsfrCheckboxSet: typeof import('@gouvminint/vue-dsfr')['DsfrCheckboxSet']
    DsfrFieldset: typeof import('@gouvminint/vue-dsfr')['DsfrFieldset']
    DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
    DsfrInput: typeof import('@gouvminint/vue-dsfr')['DsfrInput']
    DsfrInputMultiple: typeof import('@gouvminint/vue-dsfr')['DsfrInputMultiple']
    DsfrModal: typeof import('@gouvminint/vue-dsfr')['DsfrModal']
    DsfrRadioButtonSet: typeof import('@gouvminint/vue-dsfr')['DsfrRadioButtonSet']
    DsfrSelect: typeof import('@gouvminint/vue-dsfr')['DsfrSelect']
    DsfrTab: typeof import('@gouvminint/vue-dsfr')['DsfrTab']
    DsfrTabPanel: typeof import('@gouvminint/vue-dsfr')['DsfrTabPanel']
    DsfrTabs: typeof import('@gouvminint/vue-dsfr')['DsfrTabs']
    DsfrTextarea: typeof import('@gouvminint/vue-dsfr')['DsfrTextarea']
    DsfrTextArea: typeof import('@gouvminint/vue-dsfr')['DsfrTextArea']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VIcon: typeof import('@gouvminint/vue-dsfr')['VIcon']
  }
}
